### ISSUE TITLE
Negative lat/long don't work

### ISSUE THREAD

**Issue by eq2kazial** [watanabetoshinori/LocationSimulator#1]
If your lat/long are negative your app doesn't use the correct command via idevicelocation. Per their readme, you have to format negative locations such as:

$ idevicelocation 77.432332 -- -7.008373564

$ idevicelocation -- -77.432332 -7.008373564

**Comment by itsjohnye** [comment]
@watanabetoshinori Could you please fix the issue?

**Comment by watanabetoshinori** [comment]
I am very sorry that my response has taken two years.
Thank you for the pull request. I used your code as a reference and fixed the bug.
