### ISSUE TITLE
Im new to this, i'm not a coder, what do I do?

### ISSUE THREAD

**Issue by sherbsz** [watanabetoshinori/LocationSimulator#6]
Hi. I don't know what I'm doing wrong with the Location Simulator, I downloaded the app version, and whenever I connect my phone to the application, it always gives me an error message: No DeveloperDiskImage download found

Could not find a valid download link for the corresponding DeveloperDiskImage.dmg or DeveloperDiskImage.dmg.signature.

<img width="643" alt="Screen Shot 2020-09-10 at 8 23 14 PM" src="https://user-images.githubusercontent.com/71107282/92830610-7c5e6000-f3a3-11ea-8b63-0deb747a8aee.png">

It's probably something really simple, but I have no idea what I'm doing
Thanks

**Comment by Schlaubischlump** [comment]
This is the wrong project. Open the issue here: https://github.com/Schlaubischlump/LocationSimulator. I should rename the project... Sry about the confusion. 

To answer your question: Download the latest build.

**Comment by sherbsz** [comment]
Thank you so much!
